### ISSUE TITLE
The Part should not have a Record

### ISSUE THREAD

**Issue by sebastienros** [RadioSystems/RadioSystems.AzureAuthentication#3]
It is unnecessary to use a Record for settings as there is no query on their properties for filtering. You can just rely on the Infoset storage. And this also reduces the need of a migration.

**Comment by wharri220** [comment]
The problem I had here was accessing the WorkContext.CurrentSite.As<AzureSettings> in the OwinMiddleware. I still haven't found a good way to do it while registering the middlware. 

This is why I created  part record for the azure settings, so that I could access them through an IRepository instead of site settings. I would like to be able to get rid of the record. But I am unsure of how to access site settings in the Owin Middleware.

You referenced this commit as an example: https://github.com/OrchardCMS/Orchard/commit/8aa84ef0481fbb90cc4a8b1c0635df74a8a9aec7#diff-3546edeb4b86b9a2a3d1da8fd647db52R49

You seem to create the work context by grabbing the HttpContext in the app.Use() method. My problem is that the app.UseOpenIdConnectAuthentication() method is not async and does not provide me a way of accessing the Owin context. So I'm unsure how else to access the site settings. Do you have any suggestions on that problem?

**Comment by wharri220** [comment]
I've discovered I can use ISiteService to get ahold of the settings. Working to close this issues.

**Comment by sebastienros** [comment]
Great
